version: '3.2'

services:
  dev:
    build: 
      context: .devcontainer
      cache_from:
        - ghcr.io/uas-at-ucla/aviata-dev
      args:
        - BUILDKIT_INLINE_CACHE=1
    image: ghcr.io/uas-at-ucla/aviata-dev
    container_name: aviata-dev
    volumes:
      - .:/workspace:cached
    working_dir: /workspace
    command: /bin/sh -c "while sleep 1000; do :; done"
    ports:
      - 14540:14540/udp

  prod:
    build:
      context: .
      dockerfile: prod.Dockerfile
    image: ghcr.io/uas-at-ucla/aviata
