name: CI-master

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
  # Build code, run tests, and upload Docker images.
  build_test_push:
    runs-on: ubuntu-latest

    env:
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    steps:
      - uses: actions/checkout@v2

      - name: Free disk space
        run: |
          sudo swapoff -a
          sudo rm -f /swapfile
          sudo apt clean
          docker rmi $(docker image ls -aq)
          df -h

#       - name: Force-build Docker container from scratch. Only required prior to first image upload.
#         run: docker-compose build dev

      - name: Start Docker container
        run: docker-compose up --build -d dev

      - name: Build code
        run: docker-compose exec -T dev /bin/bash -c "source ~/.bashrc && ./build.sh"

      - name: Run tests
        run: docker-compose exec -T dev /bin/bash -c "source ~/.bashrc && cd controls/build && ./aviata_test"

      - name: Stop Docker container
        run: docker-compose down

      - name: Push Docker images
        if: github.event_name == 'push'
        run: ./docker_push.sh
